# Generated by Django 3.1.6 on 2021-03-16 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210316_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_following',
        ),
        migrations.AddField(
            model_name='user',
            name='user_following',
            field=models.ManyToManyField(null=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
