# Generated by Django 3.1.6 on 2021-03-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210316_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_likes', to='network.post'),
        ),
    ]
