# Generated by Django 3.1.6 on 2021-03-16 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210316_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_following',
            field=models.ManyToManyField(related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_likes', to='network.post'),
        ),
    ]
